In [1]:
import pandas as pd
import numpy as np


In [ ]:
# Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic 
# operations like: 
# a) Addition of 2 in all the element  
# b) Multiply 3 with all the elements 
# c) Divide every element by 2 

In [2]:
arr = np.array([46,47,48,49,50])
arr_add = arr + 2 
print("After adding 2:", arr_add)
arr_mul = arr * 3 
print("After multiplying by 3:", arr_mul)
arr_div = arr/2
print("After dividing by 2:", arr_div)

After adding 2: [48 49 50 51 52]
After multiplying by 3: [138 141 144 147 150]
After dividing by 2: [23.  23.5 24.  24.5 25. ]


In [ ]:
# Q.2 Questions on Basic NumPy Array: 
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
# b) Find the most frequent value and their indice(s) in the following arrays: 
# i. x = np.array([1,2,3,4,5,1,2,1,1,1]) 
# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
x = np.array([1,2,3,6,4,5])
reversed_arr = x[::-1]
print(reversed_arr)

[5 4 6 3 2 1]


In [4]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,])
values,counts = np.unique(y,return_counts=True)
most_frequent_value = values[np.argmax(counts)] 
indices = np.where(y == most_frequent_value)[0]
print(f"Most frequent in y: {most_frequent_value}, Indices: {indices}")

Most frequent in y: 1, Indices: [0 1 2]


In [ ]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access 
# elements using row and column indices as follows: 
# a) Access 1st row, 2nd column  
# b) Access 3rd row, 1st column

In [5]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
element_a = arr[0][1]
element_b = arr[2][0]
print("a) 1st row, 2nd column:", element_a)
print("b) 3rd row, 1st column:", element_b)

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


In [ ]:
# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly 
# spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, 
# shape, total elements, the data type of each element and total number of bytes consumed 
# by the array. Find the transpose of this array using reshape() attribute. Can we do the same 
# with T attribute?

In [6]:
Bhavik = np.linspace(10,100,25)
print(Bhavik)
Bhavik.shape
Bhavik.size

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


25

In [7]:
Bhavik.dtype

dtype('float64')

In [8]:
print(Bhavik.itemsize * Bhavik.size) 
print(Bhavik.nbytes)


200
200


In [9]:
Bhavik = Bhavik.reshape(5,5)
Bhavik

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ],
       [ 28.75,  32.5 ,  36.25,  40.  ,  43.75],
       [ 47.5 ,  51.25,  55.  ,  58.75,  62.5 ],
       [ 66.25,  70.  ,  73.75,  77.5 ,  81.25],
       [ 85.  ,  88.75,  92.5 ,  96.25, 100.  ]])

In [10]:
Bhavik = Bhavik.T
Bhavik

array([[ 10.  ,  28.75,  47.5 ,  66.25,  85.  ],
       [ 13.75,  32.5 ,  51.25,  70.  ,  88.75],
       [ 17.5 ,  36.25,  55.  ,  73.75,  92.5 ],
       [ 21.25,  40.  ,  58.75,  77.5 ,  96.25],
       [ 25.  ,  43.75,  62.5 ,  81.25, 100.  ]])

In [ ]:
# Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> 
# with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, 
# median, max, min, unique elements. Reshape the array to four rows and three columns and 
# name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three 
# columns and name it as resized_ ucs420_<your_name>>. 

In [11]:
ucs420_Bhavik = np.array([[10,20,30,40],
                        [50,60,70,80],
                        [90,15,20,35]])
print("Mean: ",ucs420_Bhavik.mean())
print("Median: ",np.median(ucs420_Bhavik))
print("Max: ",ucs420_Bhavik.max())
print("Min: ",ucs420_Bhavik.min())
print("Unique Elements: ",np.unique(ucs420_Bhavik))

Mean:  43.333333333333336
Median:  37.5
Max:  90
Min:  10
Unique Elements:  [10 15 20 30 35 40 50 60 70 80 90]


In [12]:
reshaped_ucs420_Bhavik = ucs420_Bhavik.reshape(4,3)
print(reshaped_ucs420_Bhavik)

[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]


In [13]:
resized_ucs420_Bhavik = np.resize(ucs420_Bhavik,(2,3))
print(resized_ucs420_Bhavik)

[[10 20 30]
 [40 50 60]]
